In [ ]:
import pandas as pd
import numpy as np

🔹 What is Data Cleaning?
Data Cleaning is the process of:

Fixing incorrect data

Handling missing values

Removing duplicates

Standardizing formats

🔹 Why is Data Preprocessing Important?
Machine Learning models:

Cannot handle missing or messy data properly

Require numerical and consistent input

In [ ]:
data = {
    "Name": ["Ram", "Sham","Ram", "Khushi", "Arya", "Sham","NaN", "Arya"],
    "Age": [25, np.nan,21,22,23,17,18,19],
    "City": ["Mumbai", "Delhi", "mumbai", "delhi","Mumbai", "Delhi","mumbai","Delhi"]
}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['Ram', 'Sham', 'Ram', 'Khushi', 'Arya', 'Sham', 'NaN', 'Arya'], 'Age': [25, nan, 21, 22, 23, 17, 18, 19], 'City': ['Mumbai', 'Delhi', 'mumbai', 'delhi', 'Mumbai', 'Delhi', 'mumbai', 'Delhi']}

     Name   Age    City
0     Ram  25.0  Mumbai
1    Sham   NaN   Delhi
2     Ram  21.0  mumbai
3  Khushi  22.0   delhi
4    Arya  23.0  Mumbai
5    Sham  17.0   Delhi
6     NaN  18.0  mumbai
7    Arya  19.0   Delhi

🔹 Common Data Issues

Missing Values → NaN

Duplicate Records

Incorrect Data Types

Inconsistent Text (Mumbai vs mumbai)

We must identify and fix these issues before using data.

In [ ]:
# First few rows
print(df.head())

# Data info
df.info()

# Summary statistics
df.describe()

     Name   Age    City
0     Ram  25.0  Mumbai
1    Sham   NaN   Delhi
2     Ram  21.0  mumbai
3  Khushi  22.0   delhi
4    Arya  23.0  Mumbai
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     7 non-null      float64
 2   City    8 non-null      object
dtypes: float64(1), object(2)
memory usage: 324.0+ bytes

             Age
count   7.000000
mean   20.714286
std     2.870208
min    17.000000
25%    18.500000
50%    21.000000
75%    22.500000
max    25.000000

In [ ]:
df.isnull()

df.isnull().sum()

Name    0
Age     1
City    0
dtype: int64

In [ ]:
df_drop = df.dropna()
df_drop

     Name   Age    City
0     Ram  25.0  Mumbai
2     Ram  21.0  mumbai
3  Khushi  22.0   delhi
4    Arya  23.0  Mumbai
5    Sham  17.0   Delhi
6     NaN  18.0  mumbai
7    Arya  19.0   Delhi

In [ ]:
df["Age"]= df["Age"].fillna(df["Age"].mean())
df["Name"]= df["Name"].fillna(df["Name"].mode()[0])

df

     Name        Age    City
0     Ram  25.000000  Mumbai
1    Sham  20.714286   Delhi
2     Ram  21.000000  mumbai
3  Khushi  22.000000   delhi
4    Arya  23.000000  Mumbai
5    Sham  17.000000   Delhi
6    Sham  18.000000  mumbai
7    Arya  19.000000   Delhi

In [ ]:
print("\nMean of age: ")
print(df["Age"].mean())

Mean of age:
20.714285714285715

**🔹 Selecting Multiple Columns**

To work on multiple columns together:

✅ Syntax:

df[["col1", "col2"]]

🔹 Why use this?

Apply same operation on multiple columns

Clean multiple columns at once

Save time and avoid repetition

In [ ]:
new_data = {
    "Name": ["Ram", "Sham","Ram", "Khushi", "Arya", "Sham","Sham", "Arya"],
    "Age": [25, np.nan,21,22,23,17,18,19],
    "Salary":[20000,25000,52000,45000,654000,np.nan,np.nan,20140],
    "City":["Mumbai", "Delhi", "mumbai", "delhi","Mumbai", "Delhi","mumbai","Delhi"]
}
df = pd.DataFrame(new_data)
df

     Name   Age    Salary    City
0     Ram  25.0   20000.0  Mumbai
1    Sham   NaN   25000.0   Delhi
2     Ram  21.0   52000.0  mumbai
3  Khushi  22.0   45000.0   delhi
4    Arya  23.0  654000.0  Mumbai
5    Sham  17.0       NaN   Delhi
6    Sham  18.0       NaN  mumbai
7    Arya  19.0   20140.0   Delhi

In [ ]:
# Fill multiple columns with mean
df[["Age","Salary"]] =df[["Age", "Salary"]].fillna(df[["Age","Salary"]].mean())
df

     Name        Age         Salary    City
0     Ram  25.000000   20000.000000  Mumbai
1    Sham  20.714286   25000.000000   Delhi
2     Ram  21.000000   52000.000000  mumbai
3  Khushi  22.000000   45000.000000   delhi
4    Arya  23.000000  654000.000000  Mumbai
5    Sham  17.000000  136023.333333   Delhi
6    Sham  18.000000  136023.333333  mumbai
7    Arya  19.000000   20140.000000   Delhi

In [ ]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

     Name  Age  Salary    City
0     Ram   25   20000  Mumbai
1    Sham   20   25000   Delhi
2     Ram   21   52000  mumbai
3  Khushi   22   45000   delhi
4    Arya   23  654000  Mumbai
5    Sham   17  136023   Delhi
6    Sham   18  136023  mumbai
7    Arya   19   20140   Delhi

In [ ]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

     Name   Age    Salary    City
0     Ram  27.5   22000.0  Mumbai
1    Sham  22.0   27500.0   Delhi
2     Ram  23.1   57200.0  mumbai
3  Khushi  24.2   49500.0   delhi
4    Arya  25.3  719400.0  Mumbai
5    Sham  18.7  149625.3   Delhi
6    Sham  19.8  149625.3  mumbai
7    Arya  20.9   22154.0   Delhi

In [ ]:
df

     Name   Age    Salary    City
0     Ram  27.5   22000.0  Mumbai
1    Sham  22.0   27500.0   Delhi
2     Ram  23.1   57200.0  mumbai
3  Khushi  24.2   49500.0   delhi
4    Arya  25.3  719400.0  Mumbai
5    Sham  18.7  149625.3   Delhi
6    Sham  19.8  149625.3  mumbai
7    Arya  20.9   22154.0   Delhi

In [ ]:
# Replace specific values
df[["City"]]= df[["City"]].replace("Mumbai","Pune")
df

     Name        Age         Salary    City
0     Ram  25.000000   20000.000000    Pune
1    Sham  20.714286   25000.000000   Delhi
2     Ram  21.000000   52000.000000  mumbai
3  Khushi  22.000000   45000.000000   delhi
4    Arya  23.000000  654000.000000    Pune
5    Sham  17.000000  136023.333333   Delhi
6    Sham  18.000000  136023.333333  mumbai
7    Arya  19.000000   20140.000000   Delhi

In [ ]:
df

     Name   Age    Salary    City
0     Ram  27.5   22000.0  Mumbai
1    Sham  22.0   27500.0   Delhi
2     Ram  23.1   57200.0  mumbai
3  Khushi  24.2   49500.0   delhi
4    Arya  25.3  719400.0  Mumbai
5    Sham  18.7  149625.3   Delhi
6    Sham  19.8  149625.3  mumbai
7    Arya  20.9   22154.0   Delhi

🔹 **Label Encoding (Concept)**

Converts categories into numbers:

Example: Mumbai → 0

Delhi → 1

⚠️ Not ideal for nominal data (creates fake order)

🔹 Duplicate Records

Duplicate data can:

1.Bias model

2.Reduce accuracy

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

     Name   Age    Salary    City
0     Ram  27.5   22000.0  Mumbai
1    Sham  22.0   27500.0   Delhi
2     Ram  23.1   57200.0  mumbai
3  Khushi  24.2   49500.0   delhi
4    Arya  25.3  719400.0  Mumbai
5    Sham  18.7  149625.3   Delhi
6    Sham  19.8  149625.3  mumbai
7    Arya  20.9   22154.0   Delhi

In [ ]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
#FEMALE female Female FeMale
df2

     Name   Age    Salary    City
0     Ram  27.5   22000.0  MUMBAI
1    Sham  22.0   27500.0   DELHI
2     Ram  23.1   57200.0  MUMBAI
3  Khushi  24.2   49500.0   DELHI
4    Arya  25.3  719400.0  MUMBAI
5    Sham  18.7  149625.3   DELHI
6    Sham  19.8  149625.3  MUMBAI
7    Arya  20.9   22154.0   DELHI

In [ ]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
df2

     Name  Age    Salary    City
0     Ram   27   22000.0  MUMBAI
1    Sham   22   27500.0   DELHI
2     Ram   23   57200.0  MUMBAI
3  Khushi   24   49500.0   DELHI
4    Arya   25  719400.0  MUMBAI
5    Sham   18  149625.3   DELHI
6    Sham   19  149625.3  MUMBAI
7    Arya   20   22154.0   DELHI

**🌧️ Rainfall Dataset Cleaning**

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving rainfall.csv to rainfall.csv

In [ ]:
# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

Uploaded file: rainfall.csv

In [ ]:
import pandas as pd

# Load the uploaded file
df = pd.read_csv(file_name)

df.head()

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             Rainy
1  2022-01-02       8.2         17.8      65.0         5.2             Rainy
2  2022-01-03       0.0         20.1      52.0         3.1             Sunny
3  2022-01-04       3.7         18.6      71.0         6.7             Rainy
4  2022-01-05      21.1         14.8      82.0         9.3             Rainy

 Data Cleaning Operations on rainfall.**csv**

In [ ]:
df.head()

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

date                 0
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

**🔹 Convert Date Column**

Convert string → datetime format

In [ ]:
df["date"] = df["date"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     datetime64[ns]
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.7+ KB

🔹 Handle Missing Values

Numerical Columns:

  1.rainfall

  2.temperature

  3.humidity

  4.wind_speed

➡️ Fill with mean

Categorical:

   weather_condition

➡️ Fill with mode

In [ ]:
# Numerical columns
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

# Check missing values
print(df.isnull().sum())

date                 1
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

In [ ]:
df["weather_condition"] = df["weather_condition"].str.lower()

df["weather_condition"].unique()

df.head()

        date  rainfall  temperature  humidity  wind_speed weather_condition
0 2022-01-01      12.5         15.2      78.0         8.5             rainy
1 2022-01-02       8.2         17.8      65.0         5.2             rainy
2 2022-01-03       0.0         20.1      52.0         3.1             sunny
3 2022-01-04       3.7         18.6      71.0         6.7             rainy
4 2022-01-05      21.1         14.8      82.0         9.3             rainy

In [ ]:
df.to_csv("cleaned_rainfall.csv", index=False)

# Download
files.download("cleaned_rainfall.csv")

In [ ]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

**🎓 Student Performance Dataset – Data Cleaning**

In [ ]:
import pandas as pd
import numpy as np

data = {
    "name": ["Arya", "Sara", "Shruti", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

     name   age  gender  marks  attendance    city
0    Arya  20.0    Male     85        90.0  Mumbai
1    Sara  21.0  female     90        85.0   Delhi
2  Shruti   NaN    Male    105        80.0  mumbai
3    Amit  20.0    Male     85        90.0  Mumbai
4    None  19.0  FEMALE     -5         NaN    Pune

In [ ]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      int64
 4   attendance  4 non-null      float64
 5   city        5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

             age       marks  attendance
count   4.000000    5.000000    4.000000
mean   20.000000   72.000000   86.250000
std     0.816497   43.817805    4.787136
min    19.000000   -5.000000   80.000000
25%    19.750000   85.000000   83.750000
50%    20.000000   85.000000   87.500000
75%    20.250000   90.000000   90.000000
max    21.000000  105.000000   90.000000

🔹 Handling Missing Values

age → mean

attendance → mean

name → "Unknown"

In [ ]:
df["gender"] = df["gender"].str.lower()
df["city"] = df["city"].str.lower()
df

      name   age  gender  marks  attendance    city
0     Arya  20.0    male     85       90.00  mumbai
1     Sara  21.0  female     90       85.00   delhi
2   Shruti  20.0    male    105       80.00  mumbai
3     Amit  20.0    male     85       90.00  mumbai
4  Unknown  19.0  female     -5       86.25    pune

In [ ]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]
df

   name   age  gender  marks  attendance    city
0  Arya  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai

In [ ]:
df.isnull().sum()

name          0
age           0
gender        0
marks         0
attendance    0
city          0
dtype: int64

In [ ]:
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype in ['int64', 'float64']:
            df[col] = df[col].fillna(df[col].mean())
        else:
            df[col] = df[col].fillna(df[col].mode()[0])
df

   name   age  gender  marks  attendance    city
0  Arya  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai

In [ ]:
df = df.drop_duplicates()
df

   name   age  gender  marks  attendance    city
0  Arya  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai

In [ ]:
df.columns = df.columns.str.lower()
df

   name   age  gender  marks  attendance    city
0  Arya  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai